language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
- linux
ruby: 2.2.0
before_install:
 - sudo chmod 775 dependencies.sh
 - sudo ./dependencies.sh;
script:
- cd ~/build/AdrienJarretier/CamlCompiler
- make all
- cd bin/Release
- ./camlCompiler --test