language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
os:
- linux
# - osx
ruby: 2.2.0
before_install:
- sudo apt-get install libgtest-dev
install:
- sudo apt-get install cmake # install cmake
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make clean
- sudo make all
- sudo cp *.a /usr/lib
script: 
- cd ~/build/AdrienJarretier/CamlCompiler
- make all
- cd /bin/Release
- ./camlCompiler --test
branches:
  only:
  - setupTest